version: '3.7'

# Similar to Scalingo Starter 16G configuration
# https://scalingo.com/pricing/osc-fr1
services:
  database:
    image: postgres:12.7-alpine
    container_name: database
    restart: always
    command: postgres
      -c max_wal_size=2GB
      -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
      -c work_mem=8MB
    environment:
      POSTGRES_DB: database
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./configure-schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 16GB
